export const normalQuestions = {
  never: [
    "En ole viikon sisään syönyt lattialle tippunutta ruokaa",
    "En ole teeskennellyt tietäväni julkkiksen, mistä muut puhuvat",
    "En ole koskaan valehdellut ikääni",
    "En ole koskaan varastanut ruokaa",
    "En ole joutunut heitetyksi ulos baarista",
    "En ole koskaan nukahtanut baariin",
    "En ole koskaan stalkannut ketään somessa",
    "En ole oksentanut baarin lattialle",
    "En ole ostanut viimeisillä rahoillani alkoholia ruoan sijaan",
    "En ole koskaan kärsinyt useamman päivän krapulaa",
    "En ole koskaan nukkunut opiskelutoverini kanssa",
    "En ole koskaan sammunut ennen klo 21",
    "En ole koskaan maksanut juomasta yli 10e",
    "En ole koskaan saanut wc-pönttöä tukkoon",
    "En ole koskaan tehnyt soijanistipataa",
    "En ole koskaan kolaroinut (kuskina)",
    "En ole koskaan ottanut tatuointia",
    "En ole koskaan kokenut unihalvausta",
    "En ole koskaan pissannut suihkuun",
    "Housuni eivät ole koskaan revenneet julkisella paikalla",
    "En ole koskaan leikannut omia hiuksiani itse",
    "En ole koskaan vastannut puhelimeen pöntöllä",
    "En ole koskaan pitänyt jonkun muun alusvaatteita",
    "En ole koskaan viettänyt yötä sairaalassa",
    "En ole koskaan ajanut manuaalia",
    "En ole koskaan itkenyt julkisessa kulkuvälineessä",
    "En ole koskaan käynyt yökkäreissä ulkona",
    "En ole koskaan tutustunut johonkuhun baarissa",
    "En ole koskaan oksentanut punaista (punaviini)",
    "En ole koskaan matkustanut yksin",
    "En ole koskaan varastanut jotain ravintolasta",
    "En ole koskaan suudellut ihmistä jonka tapasin alle 2h sitten",
    "En ole koskaan harrastanut seksiä yli 5 vuoden ikäerolla",
    "En ole koskaan hypännyt benjihyppyä",
    "En joudu koskaan miettimään kumpi on oikea ja kumpi vasen",
    "En ole koskaan sekoittanut harakkaa ja varista",
    "En ole koskaan omistanut tablettia",
    "En koskaan puhu jonkun päälle",
    "En ole koskaan käyttänyt ei aitoja henkkareita",
    "En ole koskaan saanut tikkejä",
    "En ole koskaan ollut allerginen millekään",
    "En ole koskaan itkenyt työpaikallani",
    "En ole koskaan kerryttänyt yli 20k nimeeni",
    "En ole koskaan omistanut Tamagotchia",
    "En ole koskaan ketjupolttanut (tupakkaa)",
    "En ole koskaan laulanut baarissa karaokea",
    "En ole koskaan pelannut Pokemon-peliä",
    "En ole koskaan omistanut Wii-konsolia",
    "En ole koskaan omistanut Nintendoa",
    "En ole koskaan pelannut Howrsea tai Gosupermodelia",
    "En ole koskaan pelannut Habboa tai Panfua",
    "Tiedän, kuka on Aija Puurtinen",
    "En ole koskaan omistanut Uggeja",
    "En ole koskaan fanittanut Hopeanuolta",
    "En osaa Petri Nygårdin biisiä ulkoa",
    "Tiesin, että Petri Nygård on asunut Toijalassa",
    "En ole koskaan käynyt Yyterissä",
    "En ole koskaan käynyt Kalajoen hiekkasärkillä",
    "En ole koskaan käynyt Lapin maakunnassa",
    "En omista osakkeita",
    "En ole koskaan omistanut hamsteria/gerbiiliä yms",
    "En ole koskaan pelannut Super Mario -peliä",
    "En ole koskaan varastanut vanhemmiltani alkoholia",
    "En ole koskaan juonut ES energiajuomaa",
    "En ole koskaan onnistuneesti kalastanut",
    "En ole koskaan joogannut",
    "En ole koskaan unohtanut tamponia yli 8h ajaksi",
    "En ole koskaan juossut 10km",
    "En ole viimeisen vuoden sisään lukenut kokonaista kirjaa",
    "En osaa tehdä kärrynpyörää",
    "En osaa tehdä volttia",
    "En pidä sushista",
    "En omaa 'caught during sex' tarinaa",
    "En ole koskaan ottanut itsestäni rivoa kuvaa",
    "En ole koskaan suudellut julkisella paikalla",
    "En ole koskaan suudellut ketään, kenen nimeä en vielä tiedä",
    "En ole koskaan flirtannut viestitse",
    "En ole koskaan käynyt seksitautitesteissä",
    "En ole koskaan pelännyt tulleeni/saaneeni jonkun raskaaksi",
    "En ole koskaan omistanut yli 5 seksuaaliterveysvälinettä",
    "En ole koskaan ollut osana seksionnettomuutta",
    "En ole koskaan ihastunut yli 6 kertaa",
    "En ole koskaan langennut lukemaan horoskoopeista",
    "En ole koskaan uskonut omistanut kristalleja",
    "En ole koskaan kirjoittanut omaa juomapeliä :D",
    "En ole koskaan vahingossa tykännyt IG kuvasta",
    "En ole koskaan seurustellut yli 2 vuotta",
    "En ole koskaan seurustellut yli vuotta",
    "En ole koskaan toivonut kuolemaa krapulassa",
    "En ole koskaan saanut sakkoja",
    "En ole koskaan kuluttanut yli 100e baari-illassa",
    "En ole koskaan matkustanut ratikassa pummilla",
    "En ole koskaan muokannut hiustyyliäni ison elämänmuutoksen jälkeen"

  ],
  tasks: [
    "Päättäkää kategoria (esim. puhelinmerkit) ja sanokaa vuorotellen siihen kuuluvia asiota. Jos ei keksi, juo.",
    "Olet pelin ajan kysymysmestari. Jos kysymykseesi vastaa, joutuu juomaan 3.",
    "Tehkää sana kerrallaan tarina, jossa jokainen sanoo vuorollaan yhden sanan edellisten lisäksi. Se kehen tarina päättyy juo 3.",
    "Juot yhden, vasemmalla puolellasi juodaan 2, hänen vasemmalla 3.. viimeiseen pelaajaan asti",
    "Ota 3.",
    "Näytä viimeisin kuva puhelimestasi. Jos se ei ole hauska, juo.",
    "Juo shotti.",
    "Kehu jotain pelaajaa käyttämällä sanaa 'mehukas'",
    "Tee hassu tanssi",
    "Juo, jos pidät enemmän kissoista, kuin koirista",
    "Ootko saanu glow-upin? Kerro ja juo",
    "Kerro vitsi. Huonolle vitsille joudut juomaan.",
    "Sano ruoka josta KUKAAN ei tykkää. Tykkääjät juo.",
    "Eka joka laittaa puhelimesta salaman päälle ja pyllistää, saa antaa 5 hörppyä.",
    "Varatut juo",
    "Sinkut juo 3 yksinäisyyteensä",
    "Jos olet jakanut hammasharjaa jonkun muun kanssa, juo.",
    "Kerro balaklavan ja baklavan ero. Muuten juot 3.",
    "Montako avaamatonta snäppiä sulla on? Niin monta hörppyä otat.",
    "Kehu vieruskaveriasi. Jos hän ei tykännyt kehuista, juot.",
    "Se, joka on eniten selvä juo juomansa loppuun.",
    "Juo 1 per omistamasi seksuaaliterveysväline",
    "Pelatkaa hirsipuu. Häviäjä(t) juo.",
    "Eniten promilleja veressä ottaa väliveden.",
    "Keksikää totuus vai tehtävä",
    "Näytä google historiasi muille.",
    "Jos käytät :3 tai <3 juo.",
    "Juo jos olet oikealla puolella olevaa pidempi",
    "Ryhmäkuva aika! Tylsin pose juo.",
    "Pelaa kivi-paperi-sakset sen henkilön kanssa, joka on sinua kauimpana. Häviäjä juo.",
    "Jokainen sanoo vuorotellen jonkun pikaruokaketjun. Jos ei keksi, juo.",
    "Bodycount = hörppyjen määrä.",
    "Juo jos pidät enemmän koirista, kuin kissoista.",
    "Kaikki, jotka nukkuu sukat jalassa juo! Let the dogs out.",
    "Kerro miten tapasit pelin vetäjän.",
    "Saat antaa 5 hörppyä - vettä tai alkoholia.",
    "Androidin omistajat juo!",
    "Iphone omistajat ottaa shotin.",
    "Vähiten vaatetta päällä juo, jotta tulisi lämmin :)",
    "Jos olet joskus juonut yksin… juo!",
    "Jokainen pelaaja laittaa sormen hetkeksi tölkin ympärille. Lasketaan 3, kolmosella arvaat montako sormea jää. Väärä arvaus juo.",
    "LATTIA ON LAAVAA. Jos paloit, juot.",
    "VESIPUTOUS",
    "YLLÄTYSKYYKKY! Jos ei kyykkää niin juo.",
    "Silmät kii näyttäkää sormilla numero 1-5. Vähemmistö numero juo."
  ]
};
