export const normalQuestions = {
  never: [
    "En ole viikon sisään syönyt jotain lattialta",
    "En ole teeskennellyt tietäväni julkkiksen, mistä muut puhuvat",
    "En ole koskaan valehdellut ikääni",
    "En ole koskaan varastanut ruokaa",
    "En ole joutunut heitetyksi ulos baarista",
    "En ole koskaan stalkannut ketään somessa",
    "En ole oksentanut baariin (aei vessaan)",
    "En ole ostanut viimeisillä rahoillani alkoholia ruoan sijaan",
    "En ole koskaan kärsinyt useamman päivän kestoista krapulaa",
    "En ole koskaan nukkunut opiskelutoverini kanssa",
    "En ole koskaan sammunut ennen klo 21"
  ],
  tasks: [
    "Päättäkää kategoria (esim. puhelinmerkit) ja sanokaa vuorotellen siihen kuuluvia asiota. Jos ei enää keksi 10s sisään uutta, juo 3.",
    "Olet nyt kysymysmestari. Jos kysymykseesi vastaa, joutuu juomaan 3. Mestareita voi olla vain 1 kerrallaan.",
    "Tehkää sana kerrallaan tarina (pitkä virke), jossa jokainen sanoo vuorollaan yhden sanan. Se kehen tarina päättyy juo 3.",
    "Juot yhden, vasemmalla puolellasi juodaan 2, hänen vasemmalla 3, ..., viimeiseen pelaajaan asti",
    "Ota 3",
    "Flirttaa vieressä istuvalle",
    "Näytä viimeisin kuva puhelimestasi. Jos se ei ole hauska niin anna jonkun swipettää ja ota eka johon sormi osuu",
    "Juo shotti.",
    "Kehu jotain pelaajaa käyttämällä sanaa 'mehukas'",
    "Tee hassu tanssi",
    "Juo, jos pidät enemmän kissoista, kuin koirista",
    "Ootko saanu glow-upin? Kerro ja juo",
    "Kerro vitsi. Huonolle vitsille joudut juomaan.",
    "Sano ruoka josta KUKAAN ei tykkää. Tykkääjät juo.",
    "Eka joka laittaa puhelimesta salaman päälle ja pyllistää, saa antaa 5 hörppyä.",
    "Varatut juo",
    "Sinkut juo 3 yksinäisyyteensä",
    "Jos olet jakanut hammasharjaa jonkun muun kanssa, juo - etanoli puhdistaa suuta",
    "Kerro balaklavan ja baklavan ero. Muuten juot 3.",
    "Montako avaamatonta snäppiä sulla on? Niin monta hörppyä otat.",
    "Kehu vieruskaveriasi. Jos hän ei tykännyt kehuista, juot.",
    "Se, joka on eniten selvä juo juomansa loppuun.",
    "Juo 1 per omistamasi seksuaaliterveysväline",
    "Hirsipuun. Häviäjä(t) juo.",
    "Eniten promilleja ottaa väliveden.",
    "Sinulle keksitään nyt totuus vai tehtävä.",
    "Näytä google historiasi - mitä olet hakenut?",
    "Jos käytät :3, :) tai :( teksteissä juo 2 hörppyä.",
    "Jos olet pidempi kuin henkilö oikealla puolellasi, joudut juomaan",
    "Ryhmäkuva aika! Tylsin tai eniten basic pose juo.",
    "Pelaa kivi-paperi-sakset sen henkilön kanssa, joka on sinua kauimpana. Häviäjä juo.",
    "Jokainen sanoo vuorotellen jonkun pikaruokaketjun. Se, kuka ei keksi enää juo.",
    "Juo jokaisen seurustelusuhteesi ja/tai panon verran hörppyjä.",
    "Jos pidät enemmän koirista, kuin kissoista, iso hörö",
    "Kaikki, jotka nukkuu sukat jalassa juo! Hyi vittu oot ällö. Let the dogs out.",
    "Kerro miten tapasit pelin vetäjän.",
    "Saat antaa 5 hörppyä. Päätät, ovatko ne vettä vai alkoholia",
    "Kaikki, joilla on Android juo!",
    "Kaikki, joilla on iPhone juo 3 höröä!",
    "Se, kenellä on vähiten vaatetta päällä juo, jotta tulisi lämmin :)",
    "Jos olet joskus juonut yksin… juo!",
    "Pelaajat laittavat sormen yhden lasin/tölkin ympärille. Sano montako sormea jää: 'SORMIA. JÄÄ. numero', ja 'numerolla' pelaajat nostavat sormet. Jos arvaat väärin, juot.",
    "LATTIA ON LAAVAA. Jokainen joka osuu tällä hetkellä lattiaan juo.",
    "VESIPUTOUS",
    "YLLÄTYSKYYKKY! ÄKKIÄ NYT!!!",
    "Kaikki muut paitsi ruudussa oleva laittaa silmät kiinni ja näyttää yhdellä kädellä jonkun numeron (1-5). He, jotka valitsevat eniten tiettyä numeroa juovat."
  ]
};
