export const normalQuestions = {
  never: [
    "En ole viimeisen viikon sisään syönyt jotain lattialta",
    "En ole koskaan teeskennellyt tuntevani julkkiksen, jonka kaikki muut tietävät",
    "En ole koskaan valehdellut ikääni",
    "En ole koskaan varastanut ruokaa",
    "En ole koskaan joutunut heitetyksi ulos baarista",
    "En ole koskaan stalkannut ketään",
    "En ole koskaan oksentanut baarissa (muualla kuin vessassa)",
    "En ole koskaan ostanut alkoholia, vaikka teki jo tiukkaa ostaa ruokaa"
  ],
  tasks: [
    "Päättäkää kategoria (esim. puhelinmerkit) ja sanokaa vuorotellen siihen kuuluvia asiota. Jos ei enää keksi 10s sisään uutta, juo 3.",
    "Pelaaja on kysymysmestari. Jos hänen kysymykseen vastaa, joutuu juomaan 3. Mestareita voi olla vain 1 kerrallaan.",
    "Tehkää sana kerrallaan tarina (pitkä virke), jossa jokainen sanoo vuorollaan yhden sanan. Se kehen tarina päättyy juo 3.",
    "Juot yhden, vasemmallasi juodaan 2, hänen vasemmalla 3, ..., viimeiseen pelaajaan asti",
    "Ota 3",
    "Flirttaile vieressä istuvalle",
    "Näytä viimeisin kuva puhelimestasi. Jos se ei ole hauska niin anna jonkun swipettää ja ota eka johon sormi osuu",
    "Juo shotti.",
    "Kehu jotakuta pelaajaa käyttämällä sanaa 'mehukas'",
    "Näytä hassu tanssi.",
    "Jos pidät enemmän kissoista, kuin koirista, hörö",
    "Turva seuraavalla vuorolla.",
    "Ootko saanu glow-upin? Kerro tarinasi ja juo.",
    "Kerro vitsi. Huonolle vitsille joudut juomaan.",
    "Kerro ruoka josta kukaan ei tykkää. Jos joku tykkääkin, joudut juomaan.",
    "Eka joka laittaa puhelimesta salaman päälle ja pyllistää, saa antaa 5 hörppyä.",
    "Varatut juo",
    "Sinkut juo 3 yksinäisyyteensä",
    "Jos olet jakanut hammasharjasi jonkun muun kanssa, juo – olet likainen ja viina puhdistaa.",
    "Kerro balaklavan ja baklavan ero. Muuten juot 3.",
    "Montako avaamatonta snäppiä sulla on? Niin monta hörppyä otat.",
    "Kehu vieruskaveriasi. Jos kehut hänen mielestä hyvin, säästyt juomiselta.",
    "Se, joka on eniten selvä juo juomansa loppuun.",
    "Kaikki, ketkä omistavat seksuaaliterveysvälineen juovat. Jos yli 3, juot kunnolla.",
    "Nyt on hirsipuu. Ruudussa oleva on pelin vetäjä, häviäjä(t) juo.",
    "Se kuka on eniten kännissä joutuu nyt juomaan vesilasin tyhjäksi.",
    "Sinulle keksitään nyt totuus vai tehtävä.",
    "Näytä google historiasi - mitä olet hakenut?",
    "Jos käytät :3, :) tai :( teksteissä juo 2 hörppyä.",
    "Jos olet pidempi kuin henkilö oikealla puolellasi, joudut juomaan",
    "Ryhmäkuva aika! Tylsin tai eniten basic pose juo.",
    "Pelaa kivi-paperi-sakset sen henkilön kanssa, joka on sinua kauimpana. Häviäjä juo.",
    "Jokainen sanoo vuorotellen jonkun pikaruokaketjun. Se, kuka ei keksi enää juo.",
    "Juo jokaisen seurustelusuhteesi ja/tai panon verran hörppyjä.",
    "Jos pidät enemmän koirista, kuin kissoista, iso hörö",
    "Kaikki, jotka nukkuu sukat jalassa juo! Hyi vittu oot ällö. Let the dogs out.",
    "Kerro miten tapasit pelin vetäjän.",
    "Saat antaa 5 hörppyä. Päätät, ovatko ne vettä vai alkoholia",
    "Kaikki, joilla on Android juo!",
    "Kaikki, joilla on iPhone juo 3 höröä!",
    "Se, kenellä on vähiten vaatetta päällä juo, jotta tulisi lämmin :)",
    "Jos olet joskus juonut yksin… juo!",
    "Pelaajat laittavat sormen yhden lasin/tölkin ympärille. Sano montako sormea jää: 'SORMIA. JÄÄ. numero', ja 'numerolla' pelaajat nostavat sormet. Jos arvaat väärin, juot.",
    "LATTIA ON LAAVAA. Jokainen joka osuu tällä hetkellä lattiaan juo.",
    "VESIPUTOUS",
    "YLLÄTYSKYYKKY! ÄKKIÄ NYT!!!",
    "Kaikki muut paitsi ruudussa oleva laittaa silmät kiinni ja näyttää yhdellä kädellä jonkun numeron (1-5). He, jotka valitsevat eniten tiettyä numeroa juovat."
  ]
};
