export const teekkariQuestions = {
  never: [
    "En ole koskaan laskenut epäoleellista integraalia huvikseni :D",
    "En ole koskaan eksynyt Hervannan kampuksella",
    "En ole koskaan laulanut teekkarilauluja julkisesti",
    "En ole koskaan maistanut pontikkaa",
    "En ole koskaan juonut kiljua",
    "En ole koskaan saanut kurssista tolppaa",
    "Keskiarvoni ei ole koskaan ollut alle 3",
    "En ole koskaan käynyt Tammerkoskessa",
    "En ole koskaan ostanut mitään Prismasta, krapulassa, haalareissa.",
    "En ole koskaan joutunut selittämään mitä siis oikeasti opiskelen",
    "En ole koskaan liimannut haalarimerkkiä kii",
    "En ole koskaan ostanut epämääräistä ruokaa Hervannassa kioskilta 01-07 välillä",
    "En ole koskaan tehnyt tenttiä krapulassa",
    "En ole koskaan tehnyt tenttiä humalassa",
    "ChatGPT ei ole koskaan tehnyt esseetä puolestani",
    "ChatGPT ei ole koskaan tehnyt matikan palautuksia puolestani",
    "En ole koskaan kirjoittanut kurssipalautteeseen mitään muuta kuin 'hyvä kurssi'",
    "En ole koskaan palauttanut 10min sisään palautusikkunan sulkeutumisesta jotain",
    "En ole koskaan pelannut Herwantapeliä",
    "En ole koskaan nukahtanu kiltaan / kerhohuoneelle",
    "En ole koskaan käynyt Skellarissa",
    "En ole koskaan kuullut skellari verseä",
    "En ole koskaan käynyt toisessa kaupungissa opiskelijatapahtumassa",
    "En ole koskaan käynyt tut/tetapk luennolla",
    "En ole koskaan nukkunut luennolla",
    "En ole koskaan oksentanut kampuksella",
    "En ole koskaan pessyt hampaitani kampuksella",
    "En ole koskaan mennyt ensimmäisellä (klo ~04) bussilla/ratikalla kotiin",
    "En ole koskaan ollut yli 36h humalassa ilman unta",
    "En ole koskaan suorittanut mallasmaratonia (lyhytkin lasketaan)",
    "En ole koskaan syönyt Zarillon 8e opiskelijabursaa",
    "En ole koskaan nauttinut Konehuoneen perjantain siipiä",
    "En ole koskaan joutunut uusimaan ruotsin tenttejä (kirjallinen/suullinen)",
    "En ole koskaan unohtanut mennä tenttiin",
    "En ole koskaan noussut seisomaan sitseillä (puhe/suolattu)",
    "En ole koskaan tehnyt kiljua",
    "En ole koskaan tehnyt viiniä",
    "En ole koskaan suorittanut emäteemua",
    "En ole koskaan koodannut Pythonilla",
    "En ole koskaan saanut matikan kurssista yli 3",
    "En ole koskaan ommellut haalarimerkkiä ompelukoneella",
    "En ole koskaan antanut toisen ihmisen ommella merkkiä haalareihini puolestani",
    "En ole koskaan antanut haalarieni hihojen koskea baarin vessan lattiaa",
    "En ole koskaan liikkunut kampuksella alasti..",
    "En ole koskaan juonut Coop Lager olutta",
    "En ole koskaan juonut K menu olutta",
    "En ole koskaan joutunut selittämään, mikä on teekkari",
    "En ole koskaan huoltanut lakkini tupsua",
    "En ole koskaan päässyt tenttiä vasta 3. kerralla läpi.",
    "En ole koskaan opiskellut aiempaa tutkintoa",
    "En ole koskaan käynyt Konetalon EXAM-luokassa",
    "En ole koskaan osallistunut Wappuun",
    "En ole koskaan käynyt krapulassa luennolla/harkassa, tms.",
    "En ole koskaan käynyt humalassa luennolla/harkassa, tms.",
    "En ole koskaan kärsinyt huijarisyndroomasta opiskelujeni suhteen",
    "En ole koskaan käynyt TUTA luennolla",
    "En ole koskaan kulkenut kolmiobussilla"
  ],
  tasks: [
    "Kaikki, jotka eivät osaa heti kertoa mikä on Bolzanon lause juovat",
    "Jos lakkisi päällinen on enemmän värillinen, kuin valkoinen, juo",
    "Näytä lempi haalarimerkkisi haalareistasi.",
    "Lempparikurssisi? Jos muut vihaavat sitä, juot.",
    "Mikä on lempi opiskelijatapahtumasi? Jos se ei ole alkoholiton, juo",
    "Se, joka kertoo ekana järjestysluvun kalsiumille saa antaa 3 hörppyä. Saa googlaa!",
    "Flirttaile kuin average teekkari",
    "Selitä Newtonin 3. laki. Jos et osaa, shotti.",
    "Selitä mitä siis oikeasti opiskelet?",
    "Fuksipisteesi jaettuna 100 = montako annat",
    "Keskiarvo sisussa = montako juot",
    "Viimeisin kurssiarvosanasi = montako annat",
    "Jos et ole päässyt läpi pakollisesta kurssista, otat shotin",
    "Kuka ravaa uusintatenteissä? Hänelle shotti.",
    "Kerro, olisitko halunnut opiskelemaan jotain muuta?",
    "Rehellisesti, pidätkö killastasi?",
    "Tee lakillasi helikopteri. Jos ei ole hattusesonki, pakko juoda...",
    "Onko suvussasi teekkareita? Juo, jos on.",
    "Juo 1 per jokainen teekkarikaverisi",
    "Juo 1 per jokainen humanistikaverisi",
    "Jos et asu Hervannassa, juo",
    "Kerro oudoin kokemuksesi Hervannasta",
    "Juo 1 per vuosi mitä läppärisi on vanha",
    "Opiskelujen ohella töissä käyvät juovat tuskaansa",
    "Juo 1 per jokainen yo-kirjoitusten L/E",
    "Kerro mikä on imaginaariluku, tai juo",
    "Juo 1 per kaverisi, joka asuu Hervannassa",
    "Luetelkaa eri kiltoja vuorotellen. Joka ei keksi enää, juo."
  ],
  spicy: [
    "En ole koskaan käynyt treffeillä teekkarin kanssa",
    "En ole koskaan harrastanut seksiä teekkarin kanssa",
    "En ole koskaan suudellut kampuksella",
    "En ole koskaan ihastunut teekkariin",
    "Millä killalla on parhaimman näköiset opiskelijat? Äänestäkää voittaja, eri mieltä olevat juo.",
    "En ole koskaan pokannut jotakuta opiskelijatapahtumassa"
  ],
};
