export const teekkariQuestions = {
  never: [
    "En ole koskaan laskenut epäoleellista integraalia huvikseni :D", /*
    "En ole koskaan yrittänyt todistaa Fermat'n lausetta",
    "En ole koskaan eksynyt Hervannan kampuksella",
    "En ole koskaan laulanut teekkarilauluja julkisesti",
    "En ole koskaan kokeillut pontikkaa",
    "En ole koskaan käynyt Tammerkoskessa",
    "En ole koskaan ostanut mitään Prismasta krapulassa haalarit päällä",
    "En ole koskaan joutunut selittämään mitä siis oikeasti opiskelen",
    "En ole koskaan liimannut haalarimerkkiä",
    "En ole koskaan ostanut epämääräistä ruokaa Hervannassa kioskilta 00-07 välillä",
    "En ole koskaan tehnyt tenttiä krapulassa",
    "ChatGPT ei ole tehnyt esseetä puolestani",
    "En ole koskaan kirjoittanut kurssipalautteeseen mitään muuta kuin 'hyvä kurssi'",
    "En ole koskaan palauttanut 10min sisään palautusikkunan sulkeutumisesta jotain",
    "Se, joka tietää tai selvittää järjestysluvun kalsiumille saa antaa 3 hörppyä.",
    "En ole koskaan pelannut Herwantapeliä",
    "En ole koskaan nukahtanu kiltaan / kerhohuoneelle",
    "En ole koskaan käynyt Skellarissa",
    "En ole käynyt toisessa kaupungissa opiskelijatapahtumassa",
    "En ole koskaan käynyt tutapk luennolla",
    "En ole koskaan nukkunut luennolla",
    "En ole oksentanut kampuksella",
    "En ole mennyt ensimmäisellä (~04) bussilla/ratikalla kotiin",
    "En ole ollut yli 24h humalassa ilman unta",
    "En ole koskaan suorittanut mallasmaratonia",
    "En ole syönyt Zarillon opiskelijabursaa",
    "En ole nauttinut Konehuoneen perjantain siipiä",
    "En ole koskaan joutunut uusimaan ruotsin tenttejä (kirjallista tai suullista)",
    "En ole koskaan unohtanut mennä tenttiin",
    "En ole koskaan noussut seisomaan sitseillä (pitämään puhetta/suolattu)",
    "En ole koskaan tehnyt kiljua",
    "En ole koskaan suorittanut emäteemua",
    "En ole koskaan ommellut merkkiä ompelukoneella",
    "En ole koskaan antanut toisen ihmisen ommella merkkejä haalariini puolestani",
    "En tiedä missä kaikki kiltahuoneet sijaitsevat",
    "En ole liikkunut kampuksella alasti",
    "En ole koskaan päässyt tenttiä vasta 3. kerralla läpi.",
    "En ole koskaan opiskellut aiempaa tutkintoa",*/
    "En ole koskaan käynyt Konetalon EXAM-luokassa"
  ],
  tasks: [
    "Valitse huora. Huorasi juo aina, kun itse juot. Huoria voi ketjuttaa.",
    "Flirttaile kuin average teekkari",
    "Selitä Newtonin 3. laki. Jos et osaa, shotti.",
    "Selitä mitä siis oikeasti opiskelet ?",
    "Fuksipisteesi jaettuna 100 = montako annat",
    "Keskiarvo sisussa = montako juot",
    "Viimeisin kurssiarvosanasi = montako annat",
    "Jos ole et päässyt läpi pakollisesta kurssista, otat shotin",
    "Kuka ravaa uusintatenteissä? Hänelle shotti."
  ]
};
