export const teekkariQuestions = {
  never: [
    "En ole koskaan laskenut epäoleellista integraalia huvikseni :D",
    "Tiedän mikä on Fermat'n lause",
    "En ole koskaan eksynyt Hervannan kampuksella",
    "En ole koskaan laulanut teekkarilauluja julkisesti",
    "En ole koskaan maistanut pontikkaa",
    "En ole koskaan juonut kiljua",
    "En ole koskaan saanut kurssista tolppaa",
    "Keskiarvoni ei ole koskaan ollut alle 3",
    "En ole koskaan käynyt Tammerkoskessa",
    "En ole koskaan ostanut mitään Prismasta krapulassa, haalareissa",
    "En ole koskaan joutunut selittämään mitä siis oikeasti opiskelen",
    "En ole koskaan liimannut haalarimerkkiä kii",
    "En ole koskaan ostanut epämääräistä ruokaa Hervannassa kioskilta 01-07 välillä",
    "En ole koskaan tehnyt tenttiä krapulassa",
    "En ole koskaan tehnyt tenttiä humalassa",
    "ChatGPT ei ole koskaan tehnyt esseetä puolestani",
    "ChatGPT ei ole koskaan tehnyt matikan palautuksia puolestani",
    "En ole koskaan kirjoittanut kurssipalautteeseen mitään muuta kuin 'hyvä kurssi'",
    "En ole koskaan palauttanut 10min sisään palautusikkunan sulkeutumisesta jotain",
    "En ole koskaan pelannut Herwantapeliä",
    "En ole koskaan nukahtanu kiltaan / kerhohuoneelle",
    "En ole koskaan käynyt Skellarissa",
    "En ole käynyt toisessa kaupungissa opiskelijatapahtumassa",
    "En ole koskaan käynyt tut/tetapk luennolla",
    "En ole koskaan nukkunut luennolla",
    "En ole oksentanut kampuksella",
    "En ole koskaan pessyt hampaitani kampuksella",
    "En ole mennyt ensimmäisellä (klo ~04) bussilla/ratikalla kotiin",
    "En ole ollut yli 36h humalassa ilman unta",
    "En ole koskaan suorittanut mallasmaratonia (lyhytkin lasketaan)",
    "En ole syönyt Zarillon 8e opiskelijabursaa",
    "En ole nauttinut Konehuoneen perjantain siipiä",
    "En ole koskaan joutunut uusimaan ruotsin tenttejä (kirjallista tai suullista)",
    "En ole koskaan unohtanut mennä tenttiin",
    "En ole koskaan noussut seisomaan sitseillä (puhe/suolattu)",
    "En ole koskaan tehnyt kiljua",
    "En ole koskaan suorittanut emäteemua",
    "En ole koskaan ommellut haalarimerkkiä ompelukoneella",
    "En ole koskaan antanut toisen ihmisen ommella merkkejä haalariini puolestani",
    "Haalarini hihat eivät ole koskaan koskeneet vessan lattiaa",
    "Ei ole kiltahuonetta, jonka sijaintia en tiedä",
    "En ole liikkunut kampuksella alasti..",
    "En ole koskaan juonut Coop Lager",
    "En ole koskaan juonut K menu olutta",
    "En ole koskaan käynyt treffeillä teekkarin kanssa",
    "En ole koskaan joutunut selittämään, mikä on teekkari",
    "En ole koskaan päässyt tenttiä vasta 3. kerralla läpi.",
    "En ole koskaan opiskellut aiempaa tutkintoa",
    "En ole koskaan käynyt Konetalon EXAM-luokassa"
  ],
  tasks: [
    "Valitse huora. Huorasi juo aina, kun itse juot. Huoria voi ketjuttaa.",
    "Se, joka kertoo ekana järjestysluvun kalsiumille saa antaa 3 hörppyä.",
    "Flirttaile kuin average teekkari",
    "Selitä Newtonin 3. laki. Jos et osaa, shotti.",
    "Selitä mitä siis oikeasti opiskelet ?",
    "Fuksipisteesi jaettuna 100 = montako annat",
    "Keskiarvo sisussa = montako juot",
    "Viimeisin kurssiarvosanasi = montako annat",
    "Jos ole et päässyt läpi pakollisesta kurssista, otat shotin",
    "Kuka ravaa uusintatenteissä? Hänelle shotti."
  ]
};
